[workspace]
members = [
    "crates/document",
    "crates/driver",
    "crates/glaphica",
    "crates/render_protocol",
    "crates/renderer",
    "crates/tiles",
    "crates/view",
]
resolver = "3"
