[workspace]
members = ["crates/brush_execution",
    "crates/code_analysis",
    "crates/document",
    "crates/driver",
    "crates/frame_scheduler",
    "crates/glaphica",
    "crates/render_protocol",
    "crates/renderer",
    "crates/tiles",
    "crates/view",
]
resolver = "3"
