[package]
name = "tiles"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "28.0.0"
pollster = "0.4.0"

[dev-dependencies]
image = { version = "0.25.5", default-features = false, features = ["jpeg", "png"] }
