[package]
name = "window_replay"
version = "0.1.0"
edition = "2024"

[dependencies]
replay_protocol = { path = "../replay_protocol" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
